### ISSUE TITLE
Update project for Java 9

### ISSUE THREAD

**Issue by monjohn** [juxt/edge#26] opened 2017-12-06 15:26 UTC
I cloned the project and tried to run it but got this error:

```sh
java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
clojure.lang.Compiler$CompilerException: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(aleph/http/client_middleware.clj:420:7)
  java.lang.ExceptionInInitializerError: 
java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
             clojure.lang.ExceptionInfo: java.lang.ExceptionInInitializerError
    file: "/var/folders/x5/t1zvsp455tb1j07y_j6tddxm0000gn/T/boot.user545993743605152703.clj"
    line: 41
```

The issue seems to be an incompatibility with Java 9.

Updating details are here: https://www.deps.co/blog/how-to-upgrade-your-clojure-projects-to-use-java-9/

**Comment by tirkarthi** [comment] 2018-04-05 16:50
The above error is fixed as of now with https://github.com/ztellman/aleph/commit/b4a49a878d73bb7db4178f7e62ddc9feb912f664 . Also I could see current version of Clojurescript causes issues with JDK 9. Latest Clojurescript release [1.10](https://clojurescript.org/news/2018-03-26-release) fixes JDK 9 compatibility issue caused by xml-bind. Relevant JIRA issue : https://dev.clojure.org/jira/browse/CLJS-2377 . Upgrading it might resolve the issue.

**Comment by delitescere** [comment] 2018-06-06 06:13
@ericstewart the `--add-modules` is a temporary fix as those EE modules are deprecated from the SE JDK and probably will disappear in Java 11.

Have you tried to explicitly add `javax.xml.bind/jaxb-api {:mvn/version "2.3.0"}` to your `deps.edn`?

**Comment by delitescere** [comment] 2018-06-06 06:18
@ericstewart try just explicitly listing `javax.xml.bind/jaxb-api {:mvn/version "2.3.0"}` in your `deps.edn` (this will also avoid issues with Java 11 when those EE modules won't be bundled into the JDK).

**Comment by SevereOverfl0w** [comment] 2018-12-22 01:03
I believe this is all working now. We have a few developers using 9+ running edge projects.

**Closed by SevereOverfl0w** 2018-12-22 01:04 UTC
