### ISSUE TITLE
boot uberjar fails

### ISSUE THREAD

**Issue by thegeez** [juxt/edge#22] opened 2017-01-05 16:06 UTC
A new clone of this project at cc9ad27bf1a77c25f6fd545a7b0c0150a9b353a7
With 
```
$ boot --version
#http://boot-clj.com
#Thu Jan 05 16:57:57 CET 2017
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_CLOJURE_VERSION=1.9.0-alpha12
BOOT_VERSION=2.6.0
```

And 
```
$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~15.10.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```

```
$ boot uberjar
Building uberjar
Compiling {sass}... 8 changed files.
Compiling ClojureScript...
• edge.js
Compiling 1/1 edge.main...
             clojure.lang.ExceptionInfo: java.io.IOException: File name too long, compiling:(yada/schema.clj:84:3)
    data: {:file "/tmp/boot.user6370988360429421521.clj", :line 61}
clojure.lang.Compiler$CompilerException: java.io.IOException: File name too long, compiling:(yada/schema.clj:84:3)
                    java.io.IOException: File name too long
                                ...  
```

**Comment by SevereOverfl0w** [comment] 2017-01-06 14:54
This looks like it's a Yada bug (pinging @malcolmsparks). May be related to https://groups.google.com/forum/#!topic/clojure/XA8U9x2AjcU

We should see if this is still an issue with yada 1.2.x

**Comment by Snorremd** [comment] 2017-01-24 08:49
Can confirm that this is still an issue with yada 1.2.0.

* Cloned cc9ad27bf1a77c25f6fd545a7b0c0150a9b353a7
* Changed yada require-statement to use "1.2.0"
* Ran `boot uberjar`.

Boot version:
```
#Tue Jan 24 09:48:35 CET 2017
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_CLOJURE_VERSION=1.9.0-alpha14
BOOT_VERSION=2.6.0
```

Java version:
```
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.10.2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
```

**Comment by SevereOverfl0w** [comment] 2017-01-24 11:28
The cause is the macro expansion of https://github.com/juxt/yada/blob/1.2.0/src/yada/schema.clj#L80-L93 which is very large as to potentially create classes that might be too long for some filesystems.

What filesystem/OS are you using when you get this? It does work on ext4 with Linux (no max path defined) and I'd wager it should work on Mac OSX using HFS+ as that has an unlimited maximum path size.

The simplest solution is to upgrade to the latest boot, and follow the example in https://github.com/adzerk-oss/boot-uberjar-example (the changes made in https://github.com/adzerk-oss/boot-uberjar-example/commit/eeddc47032520dc8e8a7bf3e7de45c402f298e7d are particularly of interest here). This will only Uberjar the entrypoint, and not any of the children. This is the behaviour that leiningen takes.

**Comment by thegeez** [comment] 2017-01-24 11:44
From the java version output for both myself and Snorremd we both are on Ubuntu.

The latest boot uberjar approach only compiles an entry point for the uberjar, the rest of the files will not be AOT compiled and show up as .clj files in the jar. This is the approach I ended up with for https://github.com/thegeez/clj-wiki too.

I believe the intent for the edge project is to have a fully AOT'ed uberjar.

**Comment by Snorremd** [comment] 2017-01-24 11:47
For the record I'm running my entire Linux install including `/home` in an `ext4` partition. I will try the latest boot uberjar approach! Thank you both for your fast replies!

**Comment by SevereOverfl0w** [comment] 2017-01-24 16:35
Both @malcolmsparks and I are able to uberjar edge in current state, but we use LUKS to encrypt our filesystem, so don't have the ecryptfs limit.

Ecryptfs on top might be the cause in both cases, doesn't ubuntu give the option to use ecryptfs for home directories? That could be the cause in both cases, if you both ticked that option during setup.

I think we should remove the `for` macro from yada in this case, if this crops up repeatedly (from other libraries) then I think Edge should consider having a flag for the uberjar task which only does the entrypoint as mentioned previously.

**Comment by Snorremd** [comment] 2017-01-24 20:32
Ubuntu does indeed give you an option to encrypt your home folder via ecryptfs during setup. I'm willing to bet that running on ecryptfs is not entirely uncommon.

**Comment by SevereOverfl0w** [comment] 2017-01-24 22:44
The result of the `for` is 176 characters long. This aligns with your findings. I've rewritten the `for` loop using `map` and the .class. With these changes this has become `77`! 

I've opened the PR here: https://github.com/juxt/yada/pull/147

**Comment by SevereOverfl0w** [comment] 2017-02-08 15:06
My PR has been merged, @Snorremd or @thegeez would you be able to try with yada 1.2.1 please? I'll try give some love to edge soon and bump all the deps!

**Comment by thegeez** [comment] 2017-02-08 22:06
Master of `edge` with `[yada "1.2.1"]` works for `boot uberjar` on my machine, thanks.

**Comment by SevereOverfl0w** [comment] 2017-02-10 16:45
Great, all pushed up! Thanks for the report.

**Closed by SevereOverfl0w** 2017-02-10 16:45 UTC
